### ISSUE TITLE
Import Expenses redesign.

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/21nautica#104]
Currently, the Import Expsenses is a problem when a vendor sends an invoice. He has to update it for EACH container and that is a very slow process. Instead, the following changes are now proposed:

* Remove "Import Expenses" text field and button from the menu bar.
* Add a Drop Down Menu Item in Import -> "Import Expenses" 

This will open the following screen:

![screen shot 2015-07-01 at 10 47 11 am](https://cloud.githubusercontent.com/assets/61500/8447982/d126d3c2-1fde-11e5-88b6-4f62cedc4de9.png)

Explanation of the numbers shown. 

1. Invoice Number is an autocomplete if it exists or if it's a new one, it should be added. If the invoice already exists, then we show a list the existing entries for all the containers and their relevant items in this screen. This is NOT an editable table. In case you need to edit, we click on edit and to opens the same modal explained in 5. below.

2. Container Number autocomplete. As the user starts typing in the container number, it should autocomplete.

3. Item Dropdown as shown. There is no "Other" option here. In case we need to add another item, it will be configured from the back-end.

4. When the item is selected, it should auto-complete the "Name" in the second column.

5. When we want to add a new entry, we click on "Add". This opens a modal window. with the form that needs to be submitted. For easiness, we have mentioned the form-type in the image BUT this is ONLY for the modal window. The table is a simple list.

6. Currency is an dropdown and should be auto-selected if we know the currency 

7. Actions - Edit. Remove. 

8. As items get added, we update the Invoice Amount dynamically. Also, we add the relevant Work Order for each container as a comma separated list.  Remarks are updatable for this import expense.

**Comment by Sameer-Tilak** [comment]
This is done.
