### ISSUE TITLE
New daily report to send to customer.

### ISSUE THREAD

**Issue by Sameer-Tilak** [joshsoftware/21nautica#106]
Add new report in daily status mail that is send to each customer. 
Columns in report should be 
BL Number, Goods Description, ETA, Equipment x Qty, Last Status Update, Remarks

Last status update - should change when any one container changes its status to next. 
Row should be removed once all container status is set to delivered.

**Comment by paritoshbotre** [comment]
Need to add new status in import as 'delivered'.

When all containers for particular import is 'delivered', then set the import status as 'delivered' from 'ready to load'.

**Comment by paritoshbotre** [comment]
Done.
