### ISSUE TITLE
BL / Container number search option

### ISSUE THREAD

**Issue by Sameer-Tilak** [joshsoftware/21nautica#109]
Need to add separate page to search BL / Container number in Bill and show the list of charges levied on it so far. 

Accept Import / Export , BL / Container, Number 
If BL then in header show Total Containers in that BL. 
Table columns - Vendor name, Invoice number, date, Item, qty, rate, amt

**Comment by Sameer-Tilak** [comment]
Need more details as below.

If searched number is BL, Then at present we do show all invoices related to that BL. 

Alongwith that also show Invoice details about all containers from that BL.

**Comment by paritoshbotre** [comment]
Done.
