### ISSUE TITLE
Export Invoicing

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/21nautica#84]
## TBL

Once the BL Payment has been made, that BL is ready to be Invoiced.				
Invoice date would be the date of Movement of the first container in that BL						
 
## Haulage.

In this case, each container once given movement for will be ready for invoice.

**Comment by anuja-joshi** [comment]
This is my logic for export invoicing-
TBL:
- when BL payment is made, invoice will be generated and made ready if it is export type of BL and invoice for that BL is not already present(beacause, In system payment for same BL can be done multiple times, but invoice should get ready when first payment is done).

- Date of invoice will be date of first movement in that BL.

For Haulage:
- Export order will be ready for invoice, If all export item in perticular order are assigned movement.

- we will have callback in export like-
```ruby
after_save :ready_export_invoice, if: (is_haulage_type? && all_containers_are_moved)
```
   `all_containers_are_moved` method will check quantity and number of containers moved are same or not.
- Date of invoice date of Movement of the first container in that order.
