### ISSUE TITLE
Rate Check Screen

### ISSUE THREAD

**Issue by anuja-joshi** [joshsoftware/21nautica#95]
This screen will show all costs associated with the BL and Total in following format -
- Import BL
  - Customer Name | BL Number | Eq X Qty | Total BL Cost | Total Import Expenses | Inv Value | Details
  - Details pop will have BL charges(Shipping Line Charges, Ocean Freight, Port Charges, Port Storage, Agency Fee) and following charges for each container: 
    - Haulage
    - Empty
    - ICD
    - Final Clearing
    - Demurrage

- Export BL
  - BL Number | Custome Name | Port of Discharge | Total Transporter Payment | Total Clearing Agent | Ocean Freight | Sales invoice value | Details
  -  Details pop will have BL charges(Ocean Freight) and following charges for each container:
     - Transporter Payment
     - Clearing Agent

**Comment by Sameer-Tilak** [comment]
No more required. So closing.
